BD_projekt/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/promed/', permanent=True)),
    path('admin/', RedirectView.as_view(url='/promed/admin/', permanent=True)),
    path('promed/', include("promed.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# static() to add URL mapping to serve static files during development (only)

promed/urls.py
from django.urls import path, include
from . import views
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf import settings

urlpatterns = [
    path('', RedirectView.as_view(url='/promed/home/', permanent=True)),
    path('home/', views.home_view, name="home"),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)), # tylko na stronie głownej się wyświetla
    ]

urlpatterns += [
    path('home/pateint', views.home_patient_view, name="home_patient"),
    path('patient/dashboard', views.patient_dashboard_view, name="patient_dashboard"),
    path('patient/details', views.patient_detail_view, name='patient_detail'),
    path('patient/search/appointments/specialization', views.appointment_search_specialization_view, name='appointment_search_specialization'),
    path('patient/search/appointments/<int:specialization_id><str:city>/', views.appointment_search_patient_view, name='appointment_search'),
    path('pateint/info/complete', views.complete_info_patient_view, name='complete_patient_info'),
    path('patient/appointment/<uuid:pk>/detail', views.cancel_appointment_view, name='detail_cancel_appointment'),
    path('patient/appointment/<uuid:pk>/cancel/complete', views.complete_cancel_appointment_view, name='complete_appointment_cancellation'),
    # Do potwierdzania wizyty przez pacjenta
    path('patient/appointment/<uuid:pk>/confirm', views.confirm_appointment_view, name='confirm_appointment'),
    path('patient/appointment/<uuid:pk>/confirm/complete', views.complete_confirm_appointment_view, name='complete_confirm_appointment'),
    path('patient/password-change/', views.PatientPasswordChangeView.as_view(), name='patient_password_change'),
    path('patient/phone-number-change/', views.change_info_patient_view, name='patient_change_phone_number'),
    
]

urlpatterns += [
    path('home/staff', views.home_staff_view, name="home_doctor"),
    path('doctor/dashboard',  views.doctor_dashboard_view, name="doctor_dashboard"),
    path('doctor/details', views.doctor_detail_view, name='doctor_detail'),
    path('doctor/past-appointments/', views.doctor_past_appointments_view, name='doctor_past_appointments'),
    path('doctor/availability/', views.doctor_availability, name='doctor_availability'),
    path('doctor/password-change/', views.DoctorPasswordChangeView.as_view(), name='doctor_password_change'),
    path('doctor/appointment/<uuid:pk>/confirm', views.confirm_appointment_doctor_view, name='confirm_appointment_doctor'),
    path('doctor/appointment/<uuid:pk>/confirm/complete', views.confirm_appointment_doctor_done_view, name='complete_appointment_confirmation'),
    path('doctor/phone-number-change/', views.change_info_doctor_view, name='doctor_change_phone_number'),
]

# Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/patient/login/', views.PatientLoginView.as_view(), name='patient_login'),
    path('accounts/patient/login/denied', views.patient_access_denied_view, name='patient_access_denied'),
    path('accounts/patient/register/', views.register_patient_view, name='patient_register'),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += [
    path('accounts/doctor/login/', views.DoctorLoginView.as_view(), name='doctor_login'),
    path('accounts/doctor/login/denied', views.doctor_access_denied_view, name='doctor_access_denied'),
    path('accounts/logout/', views.custom_logout, name='custom_logout'),
    path('accounts/logout/', views.MyLogoutView.as_view(), name='logout'), # magdzie pomogło  wylogowywaniem się
]
# path('accounts/logout/', CustomLogoutView.as_view(), name='custom_logout'),
# path('accounts/password_change/', CustomPasswordChangeView.as_view(), name='custom_password_change'),
# path('accounts/password_reset/', CustomPasswordResetView.as_view(), name='custom_password_reset'),
# path('accounts/reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='custom_password_reset_confirm'),

urlpatterns += [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('facility/<int:pk>/', views.FacilityDetailView.as_view(), name='facility_detail'),
    path('appointment/<uuid:pk>/', views.AppointmentDetailView.as_view(), name='appointment_detail'),
    path('appointment/<uuid:pk>/doctor', views.AppointmentDetailDoctorView.as_view(), name='appointment_detail_doctor'),
    path('appointment/<uuid:pk>/book/confirm', views.book_appointment_view, name='book_appointment'),
    path('appointment/<uuid:pk>/book/complete', views.complete_book_appointment_view, name='complete_appointment_booking'),
]

promed/models.py
from django.db import models
from django.conf import settings
import uuid
from datetime import datetime
from django.utils import timezone
from django.urls import reverse 
#from phonenumber_field.modelfields import PhoneNumberField <- czy się na to przerzucić
# phone_number = PhoneNumberField()
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)

    def save(self, *args, **kwargs):
        if not self.username:
            base_username = f"{self.first_name}{self.last_name}"
            username = base_username
            count = 1
            while CustomUser.objects.filter(username=username).exists():
                username = f"{base_username}{count}"
                count += 1
            self.username = username
        super().save(*args, **kwargs)

class Doctor(models.Model):
    user_id = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=9)

    def __str__(self) -> str:
        return f"{self.user_id.first_name} {self.user_id.last_name}"
    def get_absolute_url(self):
        return reverse('doctor_detail', args=[str(self.id)])

class Patient(models.Model):
    user_id = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=9, blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)

    @property # metoda tylko do odczytu (atrybut obiektu)
    def age(self):
        today = datetime.now().date()
        birthdate = self.date_of_birth
        age = today.year - birthdate.year - ((today.month, today.day) < (birthdate.month, birthdate.day))
        return age
    pesel = models.CharField(max_length=11, unique=True, blank=True, null=True) # czy powinnam to jakoś zaostrzyć???
    def __str__(self) -> str:
        return f"{self.user_id.first_name} {self.user_id.last_name}"
    def get_absolute_url(self):
        return reverse('patient_detail', args=[str(self.id)])

class Facility(models.Model):
    street_address = models.CharField(max_length=200)
    postal_code = models.CharField(max_length=6)
    city = models.CharField(max_length=200)
    VOIVODESHIP_CHOICES = [
    ('dolnośląskie', 'dolnośląskie'),
    ('kujawsko-pomorskie', 'kujawsko-pomorskie'),
    ('lubelskie', 'lubelskie'),
    ('lubuskie', 'lubuskie'),
    ('łódzkie', 'łódzkie'),
    ('małopolskie', 'małopolskie'),
    ('mazowieckie', 'mazowieckie'),
    ('opolskie', 'opolskie'),
    ('podkarpackie', 'podkarpackie'),
    ('podlaskie', 'podlaskie'),
    ('pomorskie', 'pomorskie'),
    ('śląskie', 'śląskie'),
    ('świętokrzyskie', 'świętokrzyskie'),
    ('warmińsko-mazurskie', 'warmińsko-mazurskie'),
    ('wielkopolskie', 'wielkopolskie'),
    ('zachodniopomorskie', 'zachodniopomorskie'),
    ]
    voivodeship = models.CharField(max_length=20, choices=VOIVODESHIP_CHOICES) 

    class Meta:
        verbose_name_plural = "facilities"
    
    def __str__(self):
        return f"{self.street_address}, {self.city}"
    def get_absolute_url(self):
        return reverse('facility_detail', args=[str(self.id)])
    
class Specialization(models.Model):
    name = models.CharField(max_length=200, help_text='Podaj nazwę specjalizacji.')

    def __str__(self) -> str:
        return self.name
    def get_absolute_url(self):
        return reverse('specialization_detail', args=[str(self.id)])

class Service(models.Model):
    specialzation_id = models.ForeignKey('Specialization', on_delete=models.PROTECT, null=True, blank=True)
    doctor_id = models.ForeignKey('Doctor', on_delete=models.PROTECT, null=True, blank=True) 
    DURATION_LENGTH = ( 
        ('15', '15 minut'),
        ('30', '30 minut')
    )
    duration = models.CharField(
        max_length=2, 
        choices=DURATION_LENGTH,
        default='30',
        help_text="Długość trwania usługi."
    )
    def __str__(self):
        return f"{self.specialzation_id}, {self.doctor_id}"
    def get_absolute_url(self):
        return reverse('service_detail', args=[str(self.id)])

class Appointment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unikalne ID dla danej wizyty.")
    facility_id = models.ForeignKey('Facility', on_delete=models.SET_NULL, null=True, blank=True) # NULL jak usuniemy placówkę
    service_id = models.ForeignKey('Service', on_delete=models.PROTECT, null=True, blank=True)
    appointment_time = models.DateTimeField(default=timezone.now, null=True, blank=True) 
    APPOINTMENT_STATUS = (
        ('a', 'dostepna'), #available
        ('b', 'zarezerwowana'), #booked
        ('c', 'potwierdzona'), #confirmed
        ('d', 'zakonczona'), #done
        ('u', 'niewykorzystana'), #unused
    )
    status = models.CharField(
        max_length=1, 
        choices=APPOINTMENT_STATUS,
        default='a',
        help_text="Status wizyty."
    )
    patient_id = models.ForeignKey('Patient', on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def time_to_visit(self):
        return (self.appointment_time - timezone.now()).total_seconds() / 3600 

    class Meta:
        ordering = ['appointment_time']
    
    def formatted_appointment_time(self):
        return self.appointment_time.strftime('%H:%M, %d-%m-%Y') if self.appointment_time else ''

    def __str__(self):
        formatted_time = self.formatted_appointment_time()
        return f"{self.service_id} [{formatted_time}] [{self.facility_id}]"
    def get_absolute_url(self):
        return reverse('appointment_detail', args=[str(self.id)])

promed/templates/promed/appointment_booking.html
{% extends 'promed/appointment_detail.html' %}

{% block content %}
    {{ block.super }}
    <form method="post" action="{% url 'complete_appointment_booking' pk=appointment.id %}">
        {% csrf_token %}
        <div class="container2" style="position:absolute; top: 55%; left: 30%; width: 40vw" >
            <button type="submit">Potwierdź rezerwację</button>
        </div>
    </form>
{% endblock %}

promed/templates/promed/appointment_cancellation.html
{% extends 'promed/appointment_detail.html' %}

{% block content %}
    {{ block.super }}
    <form method="post" action="{% url 'complete_appointment_cancellation' pk=appointment.id %}">
        {% csrf_token %}
        <div class="container2" style="position:absolute; top: 55%; left: 30%; width: 40vw" >
            <button type="submit">Odwołaj rezerwację</button>
        </div>
    </form>
{% endblock %}

promed/templates/promed/appointments_doctor_confirm.html
{% extends 'appointment_detail.html' %}

{% block content %}
    {{ block.super }}
    <form method="post" action="{% url 'complete_appointment_confirmation' pk=appointment.id %}">
        {% csrf_token %}
        <div class="container"  style="width:300px; left:(50% - 150px); margin: auto;" >
            <button type="submit" id="topright">Oznacz jako zrealizowaną</button>
        </div>
    </form>
{% endblock %}

promed/templates/promed/doctor_dashboard.html
{% extends 'base_doctor.html' %}
{% load static %}
{% block content %}

<div class="container2" style="position:absolute; top: 30%; left: 30%; width: 40vw">
    <h2>Nadchodzące wizyty</h2>  
    {% if reserved_appointments %}
        <h3>Zarezerwowane</h3>
        {% regroup reserved_appointments by service_id.specialzation_id as grouped_appointments %}
        {% for specialization, appointments in grouped_appointments %}
            <h3>{{ specialization }}</h3>
            <ul class="appointments">
                {% for appointment in appointments %} 
                    <li>        
                        {{ appointment.patient_id }}
                    </li>
                    <li>        
                        {{ appointment.formatted_appointment_time }} - {{ appointment.facility_id }}
                    </li>
                    <li>
                        <button><a href="{% url 'detail_cancel_appointment' pk=appointment.id %}">Szczegóły</a></button>
                    </li>
                    <br>
                {% endfor %}
            </ul>
        {% endfor %}
    {% else %}
        <p>Brak nadchodzących zarezerwowanych wizyt.</p>
    {% endif %}  

    {% if available_appointments %}
        <h3>Dostępne</h3>
        {% regroup available_appointments by service_id.specialzation_id as grouped_appointments %}
        {% for specialization, appointments in grouped_appointments %}
            <h3>{{ specialization }}</h3>
            <ul class="appointments">
                {% for appointment in appointments %} 
                    <li>        
                        {{ appointment.formatted_appointment_time }} - {{ appointment.facility_id }}
                    </li>
                    <li>
                        <button><a href="{% url 'detail_cancel_appointment' pk=appointment.id %}">Szczegóły</a></button>
                    </li>
                    <br>
                {% endfor %}
            </ul>
        {% endfor %}
    {% else %}
        <p>Brak dostępnych wizyt.</p>
    {% endif %} 

    <h2>Przeszłe wizyty</h2>
        {% if past_appointments %}
            {% regroup past_appointments by service_id.specialzation_id as grouped_past_appointments %}
            {% for specialization, appointments in grouped_past_appointments %}
                <h3>{{ specialization }}</h3>
                <ul class="appointments">
                    {% for appointment in appointments %} 
                        <li>        
                            {{ appointment.patient_id }}
                        </li>
                        <li>        
                            {{ appointment.formatted_appointment_time }} - {{ appointment.facility_id }}
                        </li>
                        <li>
                            <button><a href="{% url 'appointment_detail' pk=appointment.id %}">Szczegóły</a></button>
                        </li>
                        <br>
                    {% endfor %}
                </ul>
            {% endfor %}
        {% else %}
            <p>Brak przeszłych wizyt.</p>
        {% endif %} 
    </div>

{% endblock %}

promed/templates/promed/facility_detail.html
{% extends "base_patient.html" %}  
{% comment %}
    czy to nie powinno po jakimś innym ogólniejszym base dziedziczyć?
    i robić powrót do poprzedniej strony?
{% endcomment %}

{% block content %}
    <section>
        <h2>Szczegóły Placówki</h2>
        <p><strong>Ulica i numer budynku:</strong> {{ object.street_address }}</p>
        <p><strong>Kod pocztowy:</strong> {{ object.postal_code }}</p>
        <p><strong>Miasto:</strong> {{ object.city }}</p>
        <p><strong>Województwo:</strong> {{ object.get_voivodeship_display }}</p>
    </section>
{% endblock %}

promed/templates/promed/home.html
{% extends 'base_home.html' %}
{% load static %}
{% block content %}

<div style="display: flex; justify-content: center; height: 300px">
    <section>
        <div class="btn-help" style="width:500px; left:(50% - 250px); margin: auto;">
            <img src="{% static 'images/dzik_logo_2.png' %}" alt="Image" class="dzik-image">
            <div class="text-section">   
                <h2>
                    <form action="{% url 'home_patient' %}">
                        {% csrf_token %}
                        <button type="submit" id="topright" style="width:200px; height: 50px;">Strefa pacjenta</button>
                    </form>
                </h2>
            </div>
            <div class="text-section">  
                <h2>
                    <form action="{% url 'home_doctor' %}">
                        {% csrf_token %}
                        <button type="submit" id="topright" style="width:200px; height: 50px;">Strefa pracownika</button>
                    </form>
                </h2>
            </div>
        </div>
    </section>
</div>
{% endblock %}